root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  # // ./web -addr={addr} -dsn={address to your sql db}
  bin = "./tmp/web -addr=:6500 -dsn=web:Sambayo@10@/snippetbox?parseTime=true"
  cmd = "go build -o ./tmp/web ./cmd/web"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "static"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = 5000000000 # nanosecond
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = ["lsof -i :4000 -sTCP:LISTEN | sed 1d | awk '{print $2}' | xargs kill -9"]
  pre_cmd = ["lsof -i :4000 -sTCP:LISTEN | sed 1d | awk '{print $2}' | xargs kill -9"]
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
